watcher/user/urls.py
from django.urls import path, re_path
from .views import RegisterView, LoginView, logout_view, activate
from django.contrib.auth.views import LogoutView
from . import views

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth-register'),
    path('login/', LoginView.as_view(), name='auth-login'),
    path('logout/', logout_view, name='auth-logout'),
    # path('profile/', ProfileUpdateView.as_view(), name='auth-profile'),
    path('activate/<uidb64>/<token>/', views.activate, name='confirm_registration'),
    path('password/', views.change_password, name='change_password'),


    path('password-reset/', PasswordResetView.as_view(template_name='user/reset-password-main.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),
]

watcher/watcher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from user.views import ProfileView, UserUpdateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user.urls')),
    path('content/', include('content.urls')),
    path('', TemplateView.as_view(template_name = 'index/base.html'), name='home'),
    path("u/<str:username>/", ProfileView.as_view(), name="profile"),
    path('account/', UserUpdateView.as_view(), name="account"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watcher/user/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db.models import ImageField
from django.core.exceptions import ValidationError
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.db.models.signals import pre_save
import os
from django.dispatch import receiver

def get_avatar_path(instance, filename):
    # get the file extension
    ext = filename.split('.')[-1]
    filename = f"{instance.username}.{ext}"
    # return the upload path with the username and the extension
    return f"users/avatar/{filename}"

class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_("email address"), blank=False, null=False)
    nickname= models.CharField(_("nick name"), max_length=150, blank=True)
    phone_number= models.CharField(_('phone number'), blank=True, max_length=11)
    avatar = ImageField(upload_to=get_avatar_path, blank=True)
    bio=models.TextField(_("bio"), blank=True)
    website= models.URLField(_("website"), blank=True)
    is_varified= models.BooleanField(_("is varified"), default=False)

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username
    
    def save(self, *args, **kwargs):
        if self.avatar:
            im = Image.open(self.avatar)
            im.thumbnail((300, 300), Image.LANCZOS)
            width, height = im.size   # Get dimensions
            new_size = 200

            left = (width - new_size) // 2
            top = (height - new_size) // 2
            right = (width + new_size) // 2
            bottom = (height + new_size) // 2

            # Crop the center of the image
            im = im.crop((left, top, right, bottom))


            output = BytesIO()
            im.save(output, format='JPEG', subsampling=0, quality=95)
            output.seek(0)

            # change the imagefield value to be the newly modified image value
            self.avatar = InMemoryUploadedFile(output, 'ImageField',
                                                    "%s.jpg" % self.avatar.name.split('.')[0], 'image/jpeg',
                                                    sys.getsizeof(output), None)
            
        try:
            this = User.objects.get(id=self.id)
            if this.avatar != self.avatar:
                this.avatar.delete()
        except: pass
        super(User, self).save()

watcher/user/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserChangeForm
User = get_user_model()

#############################################
class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    def clean(self):
        if User.objects.filter(username = self.cleaned_data['username']).exists():
            raise forms.ValidationError(_("Username already exists"))
        if User.objects.filter(email = self.cleaned_data['email']).exists():
            raise forms.ValidationError(_("Email address already exists"))
        
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError("The passwords do not match.")
            
        if len(password) < 8:
            raise forms.ValidationError("The new password must be at least 8 characters long.")
        first_isalpha = password[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in password):
            raise forms.ValidationError("The new password must contain at least one letter and at least one digit or" \
                                            " punctuation character.")
        return self.cleaned_data
    
    def save(self):
        self.cleaned_data.pop("confirm_password", None)
        user = User.objects.create_user(**self.cleaned_data) #create_user => hash the password
        return user
###########################################
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        user = User.objects.filter(username = self.cleaned_data['username']).first()
        if user is None:
            raise forms.ValidationError(_("Username doesn't exists"))
        
        # if not user.check_password(self.cleaned_data['password']):
        #     raise forms.ValidationError(_("Wrong password"))

        user = authenticate(**self.cleaned_data)
        if user is None:
            raise forms.ValidationError(_("Unable to login with provided credentials"))

        self.cleaned_data['user'] = user
        return self.cleaned_data
#############################################
class UserUpdateForm(UserChangeForm):
    # Specify the fields that you want to update
    username = forms.CharField(max_length=150, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    email = forms.EmailField()
    nickname = forms.CharField(max_length=150, required=False)
    phone_number = forms.CharField(max_length=11, required=False)
    avatar = forms.ImageField(required=False)
    bio = forms.Textarea()
    website = forms.URLField(required=False)

    class Meta:
        model = User
        # Specify the fields that you want to display in the form
        fields = ("username", "email", "nickname", "phone_number", "avatar", "bio", "website")

    def __init__(self, *args, **kwargs):
        # Get the current user from the kwargs
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        # Check if the user is admin
        if not user.is_staff:
            # If not, disable the username field
            self.fields["username"].disabled = True

    def clean_username(self):
        # Validate the username field
        username = self.cleaned_data["username"]
        # Check if the username is already taken by another user
        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("A user with that username already exists.")
        return username

    def clean_email(self):
        # Validate the email field
        email = self.cleaned_data["email"]
        # Check if the email is already taken by another user
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("A user with that email already exists.")
        return email
#############################################

watcher/user/views.py
from django.contrib.auth import login, get_user_model
from django.views.generic import FormView, UpdateView, DetailView
from .forms import RegistrationForm, LoginForm, UserUpdateForm
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.core.cache import cache
from django.contrib.auth import login
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required

User = get_user_model()

class RegisterView(FormView):
    """A view class that handles user registration."""

    form_class = RegistrationForm
    template_name = 'user/register.html'

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        current_site = get_current_site(self.request)
        mail_subject = _('Activate your blog account.')
        message = render_to_string('user/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
        email.send()
        return super().form_valid(form)
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        return super(RegisterView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'form submission success')
        return reverse('home')
#############################################
def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.add_message(request, messages.INFO, 'Thank you for confirming your registration. You can now log in.again.')
        return redirect('home')

    else:
        messages.success(request, _("Invalid or expired token. Please try again."))
        return redirect('home')
#############################################
class LoginView(FormView):
    form_class = LoginForm
    template_name = 'user/login.html'
    success_url = '/'

    def form_valid(self, form):
        login(self.request, form.cleaned_data['user'])
        return super().form_valid(form)
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        return super(LoginView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'logged in')
        return reverse('home')
#############################################
# class ProfileUpdateView(LoginRequiredMixin, UpdateView):
#     model = User
#     fields = ('username', 'avatar', 'bio', 'website')
#     template_name = 'user/profile_update.html'
#     success_url = '/'

#     def get_object(self, queryset=None) :
#         return self.request.user
#############################################
@login_required
def logout_view(request):
	django_logout(request)
	messages.success(request, _("logged out successfully"))
	return redirect('home')
#############################################
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'user/change_password.html', {
        'form': form
    })
#############################################
class ProfileView(DetailView):
    model = User
    template_name = "user/profile.html"
    context_object_name = "user"

    def get_object(self):
        username = self.kwargs.get("username")
        return User.objects.get(username=username)
#############################################
class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "user/profile_update.html"

    def get_form_kwargs(self):
        # Get the default form kwargs
        kwargs = super().get_form_kwargs()
        # Add the current user as the user parameter
        kwargs["user"] = self.request.user
        return kwargs

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, 'changes saved')
        return reverse('account')

    def dispatch(self, request, *args, **kwargs):
        # Check if the user is logged in
        if request.user.is_authenticated:
            # If yes, proceed with the view
            return super().dispatch(request, *args, **kwargs)
        else:
            # If no, redirect to the login page
            return redirect('auth-login')
#############################################

watcher/templates/user/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'confirm_registration' uidb64=uid token=token %}
{% endautoescape %}

watcher/templates/user/change_password.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save changes</button>
  </form>

watcher/templates/user/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hi{% if user.is_authenticated %}, {{ user.username }}{% endif %}
</body>
</html>

watcher/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="{{form.action}}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
</body>
</html>

watcher/templates/user/login_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="{{form.action}}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
</body>
</html>

watcher/templates/user/password_reset.html
{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'auth-login' %}"  class="btn btn-outline">Cancel</a>
		</div>
	</form>
	</div>
{%endblock content%}

watcher/templates/user/password_reset_complete.html
{%block content%}
  <div class="center">
	  <form method="post" class="card" novalidate>
	  	{% csrf_token %}
	    <h2 class="text-center">Log in to your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		
		<input type="submit" value="Login" class="btn btn-primary full-width">
		<hr>
		<p class="text-center">Forgot your password <a href="{%url 'password-reset'%}">Reset Password</a></p>
		<p class="text-center">Don't have a account? <a href="{%url 'auth-register'%}">Join Now</a></p>
	</form>
</div>

{%endblock content%}

watcher/templates/user/password_reset_confirm.html
{%block content%}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>


{%endblock content%}

watcher/templates/user/password_reset_done.html
{%block content%}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

{%endblock content%}

watcher/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <h1>{{ user.username }}</h1>
    {% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="Avatar">
    {% else %}
    <p>No avatar</p>
    {% endif %}
    <p>Email: {{ user.email }}</p>
    <p>Nickname: {{ user.nickname }}</p>
    <p>Phone number: {{ user.phone_number }}</p>
    <p>Bio: {{ user.bio }}</p>
    <p>Website: <a href="{{ user.website }}">{{ user.website }}</a></p>
    <p>Verified: {{ user.is_varified }}</p>
    <p>Date joined: {{ user.date_joined }}</p>
    
</body>
</html>

watcher/templates/user/profile_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Update</title>
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}    

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_username">Username</label>
          <input type="text" id="id_username" name="username" value="{{ form.username.value }}" class="form-control" {% if form.username.disabled %}disabled{% endif %}>
        </div>
        <div class="form-group">
          <label for="id_email">Email</label>
          <input type="email" id="id_email" name="email" value="{{ form.email.value }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="id_nickname">Nickname</label>
          <input type="text" id="id_nickname" name="nickname" value="{{ form.nickname.value }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="id_phone_number">Phone number</label>
          <input type="text" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value }}" class="form-control">
        </div>
        <div class="form-group">
          <label for="id_avatar">Avatar</label>
          <input type="file" id="id_avatar" name="avatar" accept="image/*" class="form-control-file">
        </div>
        <div class="form-group">
          <label for="id_bio">Bio</label>
          <textarea id="id_bio" name="bio" rows="5" class="form-control">{{ form.bio.value }}</textarea>
        </div>
        <div class="form-group">
          <label for="id_website">Website</label>
          <input type="url" id="id_website" name="website" value="{{ form.website.value }}" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </form>
</body>
</html>

watcher/templates/user/register.html
{% include "index/header.html" %}
{% block content %}
<aside class="register-section">
  <div class="section-heading-part">
      <h3>Sign up to Watcher</h3>
  </div>
  <form id="form" action="{{form.action}}" method="post">
    <table>
      {% csrf_token %}
      {{form}}
    </table>
    <button class="button light">Submit</button>
    </form>
</aside>
  </div>
{% endblock %}
  {% include 'index/footer.html' %}

watcher/templates/user/register_old_version.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
</head>
<body>
    <form action="{{form.action}}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
</body>
</html>

watcher/templates/user/reset-password-main.html
{% include "index/header.html" %}
{% block content %}
<aside class="register-section">
  <div class="section-heading-part">
      <h3>Sign up to Watcher</h3>
  </div>
  <form id="form" action="{{form.action}}" method="post">
    <table>
      {% csrf_token %}
      {{form}}
    </table>
    <div class="reset-password-buttons-group">
        <button class="button light">Submit</button>
        <a href="{%url 'auth-login' %}" class="button dark">Cancel</a>
    </div>
    </form>
</aside>
  </div>
{% endblock %}
  {% include 'index/footer.html' %}